name: echi-listeningtest
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pip:
        - jiwer
        - matplotlib
        - soundfile
        - gdown
        - hydra-core==1.3.2
        - numpy<2.0.0
        - pandas>=2.3.2
        - pre-commit>=4.3.0
        - streamlit>=1.50.0
