defaults:
  - .@paths: paths
  - _self_

match_devices: True

noisy_seg_file: ${paths.noisy_seg_file}
ref_seg_file: ${paths.ref_seg_file}

filtered_file: ${paths.filtered_file}
filtered_store: ${paths.filtered_store}