defaults:
  - .@paths: paths
  - _self_

noisy_seg_file: ${paths.noisy_seg_file}
ref_seg_file: ${paths.ref_seg_file}

filtered_store: ${paths.filtered_store}
tsv_dir: ${paths.tsv_dir}

representation_type: ppg
representation_dir: ${paths.representation_dir}

dataset: dev
devices: [aria, ha]

sessions_file: ${paths.sessions_file}

rainbow_file: ${paths.rainbow_file}
noisy_session_file: ${paths.noisy_session_file}
ref_session_file: ${paths.ref_session_file}
segments_file: ${paths.segments_file}

animations_file: ${paths.animations_file}
test_rainbow_file: ${paths.test_rainbow_file}

listener: ???

experiment: baseline
exp_session_file: ${paths.exp_session_file}
exp_segment_video: ${paths.exp_segment_video}
exp_segment_audio: ${paths.exp_segment_audio}

overwrite: False

animation_types:
  - targetwave
  - sumwave
  - targetpower

transcript_types:
  - none
  - target only
  - all